version: '3.8'
services:
  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pomidor
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql         
    networks:
      - default

  api:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
    networks:
      - default

networks:
  default: {}

volumes:
  mariadb: {}
